name: Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0

jobs:
  test-nix:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          override: true
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: build
        run: cargo build --release
      - name: unit tests
        run: cargo test -- --nocapture
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          target: i686-pc-windows-msvc
          override: true
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: build 64-bit
        run: cargo build --release
      - name: build 32-bit
        run: cargo build --release --target i686-pc-windows-msvc
      - name: build 64-bit static
        env:
          CRT_STATIC: "true"
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release
      - name: build 32-bit static
        env:
          CRT_STATIC: "true"
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --target i686-pc-windows-msvc
      - name: unit tests
        run: cargo test -- --nocapture
